#!/bin/sh
 
# PROVIDE: yueserver
 
. /etc/rc.subr
 
name="yueserver"
rcvar=`set_rcvar`
start_cmd="yueserver_start"
stop_cmd=":"
 
load_rc_config $name
 
yueserver_start()
{
    if checkyesno ${rcvar}; then
      #setuid www
      #setgid www
      env PATH="/usr/local/www/yueserver:$PATH"
      /usr/local/bin/uwsgi --ini /usr/local/www/yueserver/yueserver.ini --daemonize /tmp/uswgi.log
    fi
}
 
run_rc_command "$1"
